### PR TITLE
Fix #591 - Path for generated source code

### LINKED ISSUE #591: [BUG] Wrong path for generated files
**Describe the bug**
Transform.newSources generates files in strange global path independent of project location.
I still can reference generated code and project (sometimes) builds fine but code usages in Intellij lights red because generated files are not in source set.

On mac is everything generated into: 
**~/Library/Application Support/kotlin/daemon**/build/generated/source/kap/main

I tried to change environment variable _"arrow.meta.generated.source.output"_ but it only changes relative path within that .../deamon folder

**To Reproduce**
I did just a small change in helloWorld example
https://github.com/jknazko/arrow-meta-examples/commit/b4ecb91fb0d074a7f09cce0f7ef394367176f2f0

Doesn't matter if I build the example from IDE or run gradlew from command line result is that helloWorld_Generated.kt and helloWorld_Generated.kt.meta are generated  in ~/Library/Application Support/kotlin/daemon

I see class file in IDE but no source
Screenshot 2020-04-28 at 13 55 11
 
Not sure if this is related or completely different bug but when I make any change to the code after first successful build then it fails with:
Screenshot 2020-04-28 at 11 37 48

I encountered multiple other errors but don't know how to reproduce, whole experience was very random, broken and usually "fixed" with a lot of intellij restarts + clear caches. But Arrow Meta has great potential.

**Expected behavior**
I would expect all generated files to be created in build folder within the project itself.

**Environment**
I always get exactly same behaviour, tried multiple gradle versions with:
Intellij IDEA CE 2019.3.3 - kotlin plugin 1.3.61
Intellij IDEA CE 2020.1 - kotlin plugin 1.3.72

I also replicated it on both MacOS and Linux

### PR DESCRIPTION
**Pull request by rachelcarmena**
## Proposal

* Absolute paths for `filePath` are not considered
* Two directories for generated sources:
  * Base directory (optional): provided via plugin option - it's provided automatically with Arrow Meta Gradle Plugin
  * Specific directory for a file (optional): provided via `filePath` in `file` - considered as a relative path

## Changes

* When generating source code:
   * Add default directory when `filePath` is not provided
   * Consider the base directory provided in `generatedSrcOutputDir` plugin option
* Remove the support of absolute paths (previous patch)
* Remove dead code
* Remove testing considerations from production code

## Pending changes

- [x] Fix [this comparison](https://github.com/arrow-kt/arrow-meta/compare/fix-591?expand=1#diff-f6b376f1922ccc8723495b30a42028ae7440d96b37f716f3dcc9f1d72f6f6918R390) because it's just related with testing
- [x] Use of plugin options during testing
- [x] Add tests with the use of plugin options
- [x] Arrow Meta Gradle Plugin - add the plugin option with the buildDir of the project by default
- [x] Previous review

## Screenshots

From an example that will be added in `arrow-meta-examples`:

Screenshott

## Notes

* Example about how to provide the plugin option (it will be documented in `arrow-meta-examples`)

```
compileKotlin {
    kotlinOptions {
        jvmTarget = "$JVM_TARGET_VERSION"
        freeCompilerArgs = [
                "-Xplugin=${project.rootDir}/create-plugin/build/libs/create-plugin-all.jar"
                ,"-P", "plugin:arrow.meta.plugin.compiler:generatedSrcOutputDir=${buildDir}"
        ]
    }
}
```

### CODE REVIEW

**Comment by rachelcarmena** [comment]
Ready for review!! :raised_hands:

**Review by raulraja — APPROVED** [review]
Awesome, thank you @rachelcarmena !🙌🙌🙌

File: compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt [hunk 1]
```diff
@@ -386,9 +387,10 @@ fun ArrayList<KtFile>.replaceFiles(file: KtFile, newFile: List<KtFile>) {
 
 fun CompilerContext.changeSource(file: KtFile, newSource: String, rootFile: KtFile, sourcePath: String? = null): KtFile {
   var virtualFile = rootFile.virtualFile
-  if (file.name != DEFAULT_META_FILE_NAME) {
-    val path = sourcePath ?: System.getProperty("arrow.meta.generated.source.output", DEFAULT_SOURCE_PATH)
-    val directory = Paths.get(path).toFile()
+  if (sourcePath != null) {
+    val baseDir = configuration?.get(ArrowMetaConfigurationKeys.GENERATED_SRC_OUTPUT_DIR, listOf(DEFAULT_BASE_DIR.toString()))?.get(0)
+    val path = Paths.get(baseDir, sourcePath)
```
Comment (danimontoya) [inline compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt:392]: `baseDir` here is nullable, not sure if it can cause any problems.. maybe we could wrap it with `?.let`

**Review by danimontoya — APPROVED** [review]
Looks good to me! only a minor nit! thank you @rachelcarmena 🙌

File: compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt (hunk 1 above)
Comment (rachelcarmena) [reply compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt]: Good catch!! Thank you so much @danimontoya :raised_hands:

**Review by i-walker — APPROVED** [review]
Thanks. @rachelcarmena 🙌

**Comment by rachelcarmena** [comment]
Thank you so much @raulraja @danimontoya @i-walker :raised_hands: :raised_hands: :raised_hands:
